version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

executors:
  meson_ubuntu_builder:
    docker:
      - image: squidfarts/ubuntu-sys:dev-deps

  meson_debain_builder:
    docker:
      - image: squidfarts/debian-sys:dev-deps

  meson_fedora_builder:
    docker:
      - image: squidfarts/fedora-sys:dev-deps

jobs:
  meson_ubuntu_build:
    executor: meson_ubuntu_builder
    steps:
      - checkout
      - run: meson setup builddir --buildtype=minsize --backend ninja
      - run: ninja -C builddir
      - run: meson test -C builddir
      
  meson_debain_build:
    executor: meson_debain_builder
    steps:
      - checkout
      - run: meson setup builddir --buildtype=minsize --backend ninja
      - run: ninja -C builddir
      - run: meson test -C builddir

  meson_fedora_build:
    executor: meson_fedora_builder
    steps:
      - checkout
      - run: meson setup builddir --buildtype=minsize --backend ninja
      - run: ninja -C builddir
      - run: meson test -C builddir

workflows:
  version: 2
  workflow:
    jobs:
      - meson_ubuntu_build
      - meson_debain_build
      - meson_fedora_build
